In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array(([6.0, 5.0, 4.0], [3.0, 2.0, 1.0]))
b

array([[6., 5., 4.],
       [3., 2., 1.]])

In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int64')

In [7]:
# Get the Size of the datatype in the ndarray
a.itemsize

8

In [8]:
# Get the number of items (product of all the numbers in shape) in an array
b.size

6

In [9]:
# Specifying datatypes:
c = np.array([1, 2, 3], dtype='int32')
c

array([1, 2, 3], dtype=int32)

## Accessing/Changing specific elements, rows, columns, etc.

In [10]:
alpha = np.array([[1, 2, 3, 4, 6], [1, 4, 8, 6, 3]])
alpha

array([[1, 2, 3, 4, 6],
       [1, 4, 8, 6, 3]])

In [11]:
# Getting mth row and nth column's element = array[m - 1, n - 1]. We can also use the negative indices as used in lists...
alpha[1, 3]

6

In [12]:
beta = np.around(np.random.random((10, 10)), decimals=2)
beta

array([[0.85, 0.29, 0.32, 0.32, 0.37, 0.52, 0.01, 0.3 , 0.66, 0.86],
       [0.89, 0.66, 0.51, 0.14, 0.54, 0.57, 0.55, 0.92, 0.04, 0.11],
       [0.25, 0.85, 0.95, 0.38, 0.37, 0.1 , 0.27, 0.94, 0.32, 0.09],
       [0.52, 0.88, 0.28, 0.09, 0.09, 0.48, 0.16, 0.42, 0.52, 0.52],
       [0.66, 0.86, 0.11, 0.62, 0.03, 0.37, 0.41, 0.49, 0.25, 0.23],
       [0.26, 0.1 , 0.17, 0.29, 0.96, 0.6 , 0.1 , 0.01, 0.31, 0.57],
       [0.1 , 0.43, 0.31, 0.4 , 0.89, 0.21, 0.48, 0.65, 0.07, 0.6 ],
       [0.95, 0.59, 0.69, 0.52, 0.9 , 0.54, 0.33, 0.23, 0.15, 0.97],
       [0.37, 0.8 , 0.03, 0.95, 0.78, 0.81, 0.88, 0.19, 0.68, 0.9 ],
       [0.02, 0.83, 0.16, 0.7 , 0.91, 0.3 , 0.3 , 0.18, 0.98, 0.5 ]])

In [13]:
# Splicing works perfectly. See these examples:
print("=== Without step ===")
print(beta[3:7, 2:5])
print("=== With step ===")
print(beta[1:8:3, 2:9:2])

=== Without step ===
[[0.28 0.09 0.09]
 [0.11 0.62 0.03]
 [0.17 0.29 0.96]
 [0.31 0.4  0.89]]
=== With step ===
[[0.51 0.54 0.55 0.04]
 [0.11 0.03 0.41 0.25]
 [0.69 0.9  0.33 0.15]]


In [14]:
# NumPy Arrays are mutable.
beta[3, 6] = 1000
beta

array([[8.5e-01, 2.9e-01, 3.2e-01, 3.2e-01, 3.7e-01, 5.2e-01, 1.0e-02,
        3.0e-01, 6.6e-01, 8.6e-01],
       [8.9e-01, 6.6e-01, 5.1e-01, 1.4e-01, 5.4e-01, 5.7e-01, 5.5e-01,
        9.2e-01, 4.0e-02, 1.1e-01],
       [2.5e-01, 8.5e-01, 9.5e-01, 3.8e-01, 3.7e-01, 1.0e-01, 2.7e-01,
        9.4e-01, 3.2e-01, 9.0e-02],
       [5.2e-01, 8.8e-01, 2.8e-01, 9.0e-02, 9.0e-02, 4.8e-01, 1.0e+03,
        4.2e-01, 5.2e-01, 5.2e-01],
       [6.6e-01, 8.6e-01, 1.1e-01, 6.2e-01, 3.0e-02, 3.7e-01, 4.1e-01,
        4.9e-01, 2.5e-01, 2.3e-01],
       [2.6e-01, 1.0e-01, 1.7e-01, 2.9e-01, 9.6e-01, 6.0e-01, 1.0e-01,
        1.0e-02, 3.1e-01, 5.7e-01],
       [1.0e-01, 4.3e-01, 3.1e-01, 4.0e-01, 8.9e-01, 2.1e-01, 4.8e-01,
        6.5e-01, 7.0e-02, 6.0e-01],
       [9.5e-01, 5.9e-01, 6.9e-01, 5.2e-01, 9.0e-01, 5.4e-01, 3.3e-01,
        2.3e-01, 1.5e-01, 9.7e-01],
       [3.7e-01, 8.0e-01, 3.0e-02, 9.5e-01, 7.8e-01, 8.1e-01, 8.8e-01,
        1.9e-01, 6.8e-01, 9.0e-01],
       [2.0e-02, 8.3e-01, 1.6e-01, 7.

In [15]:
# We can also input the change through the spliced arrays also which will reflect in the main array.
beta[1:8:3, 2:9:2] = [[-1, -1, -1, -1], [-1, -1, -1, -1], [-1, -1, -1, -1]]  # or np.full((3, 4), -1)
beta

array([[ 8.5e-01,  2.9e-01,  3.2e-01,  3.2e-01,  3.7e-01,  5.2e-01,
         1.0e-02,  3.0e-01,  6.6e-01,  8.6e-01],
       [ 8.9e-01,  6.6e-01, -1.0e+00,  1.4e-01, -1.0e+00,  5.7e-01,
        -1.0e+00,  9.2e-01, -1.0e+00,  1.1e-01],
       [ 2.5e-01,  8.5e-01,  9.5e-01,  3.8e-01,  3.7e-01,  1.0e-01,
         2.7e-01,  9.4e-01,  3.2e-01,  9.0e-02],
       [ 5.2e-01,  8.8e-01,  2.8e-01,  9.0e-02,  9.0e-02,  4.8e-01,
         1.0e+03,  4.2e-01,  5.2e-01,  5.2e-01],
       [ 6.6e-01,  8.6e-01, -1.0e+00,  6.2e-01, -1.0e+00,  3.7e-01,
        -1.0e+00,  4.9e-01, -1.0e+00,  2.3e-01],
       [ 2.6e-01,  1.0e-01,  1.7e-01,  2.9e-01,  9.6e-01,  6.0e-01,
         1.0e-01,  1.0e-02,  3.1e-01,  5.7e-01],
       [ 1.0e-01,  4.3e-01,  3.1e-01,  4.0e-01,  8.9e-01,  2.1e-01,
         4.8e-01,  6.5e-01,  7.0e-02,  6.0e-01],
       [ 9.5e-01,  5.9e-01, -1.0e+00,  5.2e-01, -1.0e+00,  5.4e-01,
        -1.0e+00,  2.3e-01, -1.0e+00,  9.7e-01],
       [ 3.7e-01,  8.0e-01,  3.0e-02,  9.5e-01,  7.8e-01,  8.1e-

## Initializing Different Types of Arrays

In [16]:
# All zeroes matrix
null = np.zeros((3, 4))
null

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# All 'ones' matrix
ones = np.ones((4, 3, 2), dtype='int32')
ones

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [18]:
# Any other number
full = np.full((3, 2), 99)
full

array([[99, 99],
       [99, 99],
       [99, 99]])

In [19]:
# To take the dimensions of a matrix and fill it with a number: (Note: The first argument is an array, not its dimensions.)
full_like = np.full_like(b, 6)
full_like

array([[6., 6., 6.],
       [6., 6., 6.]])

### Random Arrays

In [20]:
# Type 1: Argument is the dimension Iterable
np.random.random_sample((4, 2))

array([[0.95159957, 0.91433105],
       [0.11810994, 0.16619936],
       [0.86903385, 0.24294173],
       [0.57863916, 0.84659294]])

In [21]:
# Type 2: Unpacked Arguments
np.random.rand(4, 2)

array([[0.56680864, 0.68877682],
       [0.70286755, 0.98975496],
       [0.39952415, 0.07396648],
       [0.7481637 , 0.59504961]])