# NumPy (Source: KeithGalli)

In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array(([6.0, 5.0, 4.0], [3.0, 2.0, 1.0]))
b

array([[6., 5., 4.],
       [3., 2., 1.]])

In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int64')

In [7]:
# Get the Size of the datatype in the ndarray
a.itemsize

8

In [8]:
# Get the number of items (product of all the numbers in shape) in an array
b.size

6

In [9]:
# Specifying datatypes:
c = np.array([1, 2, 3], dtype='int32')
c

array([1, 2, 3], dtype=int32)

## Accessing/Changing specific elements, rows, columns, etc.

In [10]:
alpha = np.array([[1, 2, 3, 4, 6], [1, 4, 8, 6, 3]])
alpha

array([[1, 2, 3, 4, 6],
       [1, 4, 8, 6, 3]])

In [11]:
# Getting mth row and nth column's element = array[m - 1, n - 1]. We can also use the negative indices as used in lists...
alpha[1, 3]

6

In [12]:
beta = np.around(np.random.random((10, 10)), decimals=2)
beta

array([[0.46, 0.01, 0.94, 0.73, 0.46, 0.6 , 0.48, 0.47, 0.54, 0.79],
       [0.63, 0.66, 0.8 , 0.85, 0.48, 0.19, 0.35, 0.95, 0.39, 0.36],
       [0.21, 0.07, 0.85, 0.75, 0.97, 0.47, 0.24, 0.32, 0.98, 0.59],
       [0.98, 0.38, 0.04, 0.13, 0.06, 0.01, 0.92, 0.98, 0.45, 0.66],
       [0.01, 0.52, 0.5 , 0.11, 0.67, 0.86, 0.89, 0.88, 0.41, 0.69],
       [0.88, 0.66, 0.37, 0.85, 0.52, 0.22, 0.96, 0.06, 0.97, 0.48],
       [0.42, 0.5 , 0.84, 0.68, 0.42, 0.06, 0.41, 0.68, 0.22, 0.83],
       [0.79, 0.05, 0.9 , 0.79, 0.8 , 0.86, 0.94, 0.33, 0.87, 0.27],
       [0.43, 0.42, 0.58, 0.67, 0.6 , 0.03, 0.67, 0.7 , 0.28, 0.01],
       [0.67, 0.47, 0.76, 0.94, 0.59, 0.65, 0.01, 0.68, 0.09, 0.12]])

In [13]:
# Splicing works perfectly. See these examples:
print("=== Without step ===")
print(beta[3:7, 2:5])
print("=== With step ===")
print(beta[1:8:3, 2:9:2])

=== Without step ===
[[0.04 0.13 0.06]
 [0.5  0.11 0.67]
 [0.37 0.85 0.52]
 [0.84 0.68 0.42]]
=== With step ===
[[0.8  0.48 0.35 0.39]
 [0.5  0.67 0.89 0.41]
 [0.9  0.8  0.94 0.87]]


In [14]:
# NumPy Arrays are mutable.
beta[3, 6] = 1000
beta

array([[4.6e-01, 1.0e-02, 9.4e-01, 7.3e-01, 4.6e-01, 6.0e-01, 4.8e-01,
        4.7e-01, 5.4e-01, 7.9e-01],
       [6.3e-01, 6.6e-01, 8.0e-01, 8.5e-01, 4.8e-01, 1.9e-01, 3.5e-01,
        9.5e-01, 3.9e-01, 3.6e-01],
       [2.1e-01, 7.0e-02, 8.5e-01, 7.5e-01, 9.7e-01, 4.7e-01, 2.4e-01,
        3.2e-01, 9.8e-01, 5.9e-01],
       [9.8e-01, 3.8e-01, 4.0e-02, 1.3e-01, 6.0e-02, 1.0e-02, 1.0e+03,
        9.8e-01, 4.5e-01, 6.6e-01],
       [1.0e-02, 5.2e-01, 5.0e-01, 1.1e-01, 6.7e-01, 8.6e-01, 8.9e-01,
        8.8e-01, 4.1e-01, 6.9e-01],
       [8.8e-01, 6.6e-01, 3.7e-01, 8.5e-01, 5.2e-01, 2.2e-01, 9.6e-01,
        6.0e-02, 9.7e-01, 4.8e-01],
       [4.2e-01, 5.0e-01, 8.4e-01, 6.8e-01, 4.2e-01, 6.0e-02, 4.1e-01,
        6.8e-01, 2.2e-01, 8.3e-01],
       [7.9e-01, 5.0e-02, 9.0e-01, 7.9e-01, 8.0e-01, 8.6e-01, 9.4e-01,
        3.3e-01, 8.7e-01, 2.7e-01],
       [4.3e-01, 4.2e-01, 5.8e-01, 6.7e-01, 6.0e-01, 3.0e-02, 6.7e-01,
        7.0e-01, 2.8e-01, 1.0e-02],
       [6.7e-01, 4.7e-01, 7.6e-01, 9.

In [15]:
# We can also input the change through the spliced arrays also which will reflect in the main array.
beta[1:8:3, 2:9:2] = [[-1, -1, -1, -1], [-1, -1, -1, -1], [-1, -1, -1, -1]]  # or np.full((3, 4), -1)
beta

array([[ 4.6e-01,  1.0e-02,  9.4e-01,  7.3e-01,  4.6e-01,  6.0e-01,
         4.8e-01,  4.7e-01,  5.4e-01,  7.9e-01],
       [ 6.3e-01,  6.6e-01, -1.0e+00,  8.5e-01, -1.0e+00,  1.9e-01,
        -1.0e+00,  9.5e-01, -1.0e+00,  3.6e-01],
       [ 2.1e-01,  7.0e-02,  8.5e-01,  7.5e-01,  9.7e-01,  4.7e-01,
         2.4e-01,  3.2e-01,  9.8e-01,  5.9e-01],
       [ 9.8e-01,  3.8e-01,  4.0e-02,  1.3e-01,  6.0e-02,  1.0e-02,
         1.0e+03,  9.8e-01,  4.5e-01,  6.6e-01],
       [ 1.0e-02,  5.2e-01, -1.0e+00,  1.1e-01, -1.0e+00,  8.6e-01,
        -1.0e+00,  8.8e-01, -1.0e+00,  6.9e-01],
       [ 8.8e-01,  6.6e-01,  3.7e-01,  8.5e-01,  5.2e-01,  2.2e-01,
         9.6e-01,  6.0e-02,  9.7e-01,  4.8e-01],
       [ 4.2e-01,  5.0e-01,  8.4e-01,  6.8e-01,  4.2e-01,  6.0e-02,
         4.1e-01,  6.8e-01,  2.2e-01,  8.3e-01],
       [ 7.9e-01,  5.0e-02, -1.0e+00,  7.9e-01, -1.0e+00,  8.6e-01,
        -1.0e+00,  3.3e-01, -1.0e+00,  2.7e-01],
       [ 4.3e-01,  4.2e-01,  5.8e-01,  6.7e-01,  6.0e-01,  3.0e-

## Initializing Different Types of Arrays

In [16]:
# All zeroes matrix
null = np.zeros((3, 4))
null

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# All 'ones' matrix
ones = np.ones((4, 3, 2), dtype='int32')
ones

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [18]:
# Any other number
full = np.full((3, 2), 99)
full

array([[99, 99],
       [99, 99],
       [99, 99]])

In [19]:
# To take the dimensions of a matrix and fill it with a number: (Note: The first argument is an array, not its dimensions.)
full_like = np.full_like(b, 6)
full_like

array([[6., 6., 6.],
       [6., 6., 6.]])

In [20]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# Repeat an array (Kind of...)
arr_to_rep = np.array([[1, 2, 3]])
rep_array = np.repeat(arr_to_rep, 5, axis=0)
rep_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Random Arrays

In [22]:
# Type 1: Argument is the dimension Iterable
np.random.random_sample((4, 2))

array([[0.01600845, 0.62356577],
       [0.44157046, 0.41545118],
       [0.65738305, 0.11033291],
       [0.35655917, 0.17142261]])

In [23]:
# Type 2: Unpacked Arguments
np.random.rand(4, 2)

array([[0.92762275, 0.16922827],
       [0.49187279, 0.58106724],
       [0.33816973, 0.34027632],
       [0.15076887, 0.6259183 ]])

In [24]:
# Random Integer Values
np.random.randint(7, size=(3, 3))  # The 7 here is the higher limit. If we aren't passing both the low and high arguments, it is considered as high, and it should be > 0.

array([[4, 5, 4],
       [5, 4, 2],
       [0, 3, 3]])

### Exercise:
Try to get this array without manually typing:<br>
[[1, 1, 1, 1, 1],<br>
 [1, 0, 0, 0, 1],<br>
 [1, 0, 9, 0, 1],<br>
 [1, 0, 0, 0, 1],<br>
 [1, 1, 1, 1, 1]]

In [25]:
exercise = np.ones((5, 5))
exercise[1:-1, 1:-1] = np.zeros((3, 3))
exercise[2, 2] = 9
exercise

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Copying arrays

In [26]:
omegaA = np.array([1, 2, 3])
phiA = omegaA
phiA[0] = 100
omegaA

array([100,   2,   3])

In [27]:
omegaB = np.array([1, 2, 3])
phiB = omegaB.copy()
phiB[0] = 100
omegaB

array([1, 2, 3])

for more info on array initialization, checkout this [website](https://numpy.org/doc/stable/reference/routines.array-creation.html).

## Mathematics

In [28]:
a_M = np.array([1, 2, 5, 7])
print(a_M + 2, a_M * 2, sep='\n')  # a_M - 2, a_M / 2 and a_M ** 2 also work. Other overloaded operations such as +=, -= ... also work. (Broadcasting for a + 2)

[3 4 7 9]
[ 2  4 10 14]


In [29]:
# np.sin([array]) gives the sine of each term in the array
np.sin(beta)

array([[ 0.44394811,  0.00999983,  0.8075581 ,  0.66686964,  0.44394811,
         0.56464247,  0.46177918,  0.45288629,  0.51413599,  0.71035327],
       [ 0.58914476,  0.61311685, -0.84147098,  0.75128041, -0.84147098,
         0.18885889, -0.84147098,  0.8134155 , -0.84147098,  0.35227423],
       [ 0.2084599 ,  0.06994285,  0.75128041,  0.68163876,  0.82488571,
         0.45288629,  0.23770263,  0.31456656,  0.83049737,  0.55636102],
       [ 0.83049737,  0.37092047,  0.03998933,  0.12963414,  0.05996401,
         0.00999983,  0.82687954,  0.83049737,  0.43496553,  0.61311685],
       [ 0.00999983,  0.49688014, -0.84147098,  0.1097783 , -0.84147098,
         0.75784256, -0.84147098,  0.77073888, -0.84147098,  0.63653718],
       [ 0.77073888,  0.61311685,  0.36161543,  0.75128041,  0.49688014,
         0.21822962,  0.81919157,  0.05996401,  0.82488571,  0.46177918],
       [ 0.40776045,  0.47942554,  0.74464312,  0.62879302,  0.40776045,
         0.05996401,  0.39860933,  0.62879302

For a lot more, visit this [website](https://numpy.org/doc/stable/reference/routines.math.html)

## Linear Algebra

In [30]:
epsilonA = np.ones((2, 3))
epsilonA

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
epsilonB = np.full((3, 2), 2)
epsilonB

array([[2, 2],
       [2, 2],
       [2, 2]])

In [32]:
epsilonA*epsilonB

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [33]:
np.matmul(epsilonA, epsilonB)

array([[6., 6.],
       [6., 6.]])

In [34]:
epsilonC = np.identity(3)
epsilonC

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.linalg.det(epsilonC)

1.0

Reference docs 
1. https://docs.scipy.org/doc/numpy/reference/routines.Linalg.html and
2. https://numpy.org/doc/stable/reference/routines.linalg.html
for `np` Linear Algebra.
- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

## Statistics

In [36]:
stats = np.array([[3, 2, 1], [4, 5, 6]])
stats

array([[3, 2, 1],
       [4, 5, 6]])

In [37]:
np.min(stats)

1

In [38]:
np.max(stats)

6

In [39]:
np.min(stats, axis=0)

array([3, 2, 1])

In [40]:
np.max(stats, axis=1)

array([3, 6])

In [41]:
np.sum(stats)

21

In [42]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganising Arrays

In [43]:
beforeReshaping = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
beforeReshaping

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
beforeReshaping.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [45]:
beforeReshaping.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
beforeReshaping.reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
beforeReshaping.reshape(6, 2)

ValueError: cannot reshape array of size 8 into shape (6,2)

In [48]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([8, 6, 7, 5])

np.vstack([v1, v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [8, 6, 7, 5],
       [1, 2, 3, 4],
       [8, 6, 7, 5]])

In [49]:
# Horizontal stacking
h1 = np.zeros((2, 4))
h2 = np.ones((2, 2))

np.hstack([h2, h2, h1, h2])  # Even () work, not necessarily []

array([[1., 1., 1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 1.]])

## Miscellaneous

### Load data from a file

In [50]:
filedata = np.genfromtxt('data.txt', delimiter=',').astype('int32') 
# Demonstrating how to convert dtype with a function along with loading the data

filedata

array([[38, 45, 26, 37, 23, 29, 17, 48, 24, 74],
       [18, 55, 93, 77, 48, 56, 23, 29, 86, 55],
       [48, 89, 73,  9, 96, 47, 54, 72, 89, 99],
       [83, 45, 35, 17, 97, 90, 64, 20, 46, 37],
       [58,  9, 12, 32, 19, 16, 70, 11, 10, 20],
       [97, 31, 35, 70, 51, 76, 55, 90, 97, 49],
       [62, 25, 26,  9, 81, 41, 56,  1, 81, 98],
       [27, 87, 97, 37, 54, 86, 41, 84, 42, 94],
       [48, 40, 62, 34,  0,  0, 66, 14, 26, 32],
       [ 2, 31,  5, 21, 22, 64, 16, 35, 67, 81],
       [29, 45, 93, 13, 25, 29,  0, 39,  6, 72],
       [36, 23, 90, 25, 31, 38, 23, 15, 92, 40],
       [21, 25, 58,  5, 60, 81, 99, 18, 24, 22],
       [13, 67, 14,  5, 47, 86, 78, 93, 61, 98],
       [39,  0, 85, 21, 54,  4, 40, 85, 87,  3],
       [78, 75, 40, 31, 28, 33,  5, 16, 64, 38],
       [44, 60, 88, 93, 23, 74, 31, 53, 36,  0],
       [64, 29, 14, 39, 44,  3, 38, 84, 79,  2],
       [79, 42, 73, 19,  8, 50, 68,  8, 37, 47],
       [10,  6, 83, 39, 31, 65, 94, 63, 47, 41],
       [62, 51,  3, 

### Boolean Masking

In [51]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
         True],
       [False,  True,  True,  True, False,  True, False, False,  True,
         True],
       [False,  True,  True, False,  True, False,  True,  True,  True,
         True],
       [ True, False, False, False,  True,  True,  True, False, False,
        False],
       [ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False, False,  True,  True,  True,  True,  True,  True,
        False],
       [ True, False, False, False,  True, False,  True, False,  True,
         True],
       [False,  True,  True, False,  True,  True, False,  True, False,
         True],
       [False, False,  True, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False,  True, False, False,  True,
         True],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [False, False,  True, False, False, 

In [52]:
np.any(filedata > 50, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [53]:
np.all(filedata > 50, axis=1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [54]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False, False, False, False, False,
         True],
       [False,  True,  True,  True, False,  True, False, False,  True,
         True],
       [False,  True,  True, False,  True, False,  True,  True,  True,
         True],
       [ True, False, False, False,  True,  True,  True, False, False,
        False],
       [ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False, False,  True,  True,  True,  True,  True,  True,
        False],
       [ True, False, False, False,  True, False,  True, False,  True,
         True],
       [False,  True,  True, False,  True,  True, False,  True, False,
         True],
       [False, False,  True, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False,  True, False, False,  True,
         True],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [False, False,  True, False, False, 

In [55]:
(filedata > 50) and (filedata < 100)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [56]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True, False, False, False,  True, False,  True,  True, False,
        False],
       [ True, False, False,  True, False,  True, False, False, False,
        False],
       [False,  True,  True,  True, False, False, False,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [False,  True,  True, False, False, False, False, False, False,
         True],
       [False,  True,  True,  True, False,  True, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False,  True,
        False],
       [ True,  True, False,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True, False,
        False],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
        False],
       [ True,  True, False,  True,  True, 

### Advanced Indexing
We can give the index input of a `np.array` another array, or a same `ndim` array with `bool` values

In [57]:
# Boolean Indexing
filedata[filedata > 50]

array([74, 55, 93, 77, 56, 86, 55, 89, 73, 96, 54, 72, 89, 99, 83, 97, 90,
       64, 58, 70, 97, 70, 51, 76, 55, 90, 97, 62, 81, 56, 81, 98, 87, 97,
       54, 86, 84, 94, 62, 66, 64, 67, 81, 93, 72, 90, 92, 58, 60, 81, 99,
       67, 86, 78, 93, 61, 98, 85, 54, 85, 87, 78, 75, 64, 60, 88, 93, 74,
       53, 64, 84, 79, 79, 73, 68, 83, 65, 94, 63, 62, 51, 86, 73, 98, 74,
       94, 88, 64, 54, 55, 57, 56, 58, 62, 56, 74, 89, 51, 52, 76, 72, 68,
       94, 58, 74, 71, 87, 80, 60, 56, 63, 84, 60, 82, 68, 93, 65, 62, 75,
       86, 54, 68, 81, 65, 88, 94, 75, 57, 72, 82, 75, 53, 72, 69, 73, 79,
       98, 84, 63, 80, 73, 92, 66, 71, 51, 64, 98, 94, 82, 60, 60, 53, 90,
       97, 65, 77, 56, 54, 51, 84, 74, 76, 60, 97, 71, 74, 81, 53, 91, 51,
       85, 86, 99, 95, 97, 65, 86, 70, 73, 64, 97, 79, 67, 78, 99, 82, 63,
       88, 52, 78, 52, 74, 51, 84, 55, 62, 57, 56, 91, 93, 56, 85, 83, 80,
       79, 90, 56, 72, 59, 66, 75, 70, 55, 79, 80, 67, 52, 73, 59, 97, 51,
       63, 92, 61, 55, 88

Indexing with the help of arrays:

In [58]:
Array = np.array(range(1, 26)).reshape((5, 5))
Array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
Array[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [60]:
Array[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [61]:
Array[[0, 3, 4], 3:]

array([[ 4,  5],
       [19, 20],
       [24, 25]])

for more references on Indexing, checkout this [website](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html).