In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array(([6.0, 5.0, 4.0], [3.0, 2.0, 1.0]))
b

array([[6., 5., 4.],
       [3., 2., 1.]])

In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int64')

In [7]:
# Get the Size of the datatype in the ndarray
a.itemsize

8

In [8]:
# Get the number of items (product of all the numbers in shape) in an array
b.size

6

In [9]:
# Specifying datatypes:
c = np.array([1, 2, 3], dtype='int32')
c

array([1, 2, 3], dtype=int32)

## Accessing/Changing specific elements, rows, columns, etc.

In [10]:
alpha = np.array([[1, 2, 3, 4, 6], [1, 4, 8, 6, 3]])
alpha

array([[1, 2, 3, 4, 6],
       [1, 4, 8, 6, 3]])

In [11]:
# Getting mth row and nth column's element = array[m - 1, n - 1]. We can also use the negative indices as used in lists...
alpha[1, 3]

6

In [12]:
beta = np.around(np.random.random((10, 10)), decimals=2)
beta

array([[0.94, 0.74, 0.44, 0.11, 0.18, 0.2 , 0.91, 0.42, 0.56, 0.43],
       [0.69, 0.78, 0.01, 0.25, 0.92, 0.57, 0.88, 0.78, 0.43, 0.09],
       [0.74, 0.37, 0.89, 0.3 , 0.78, 0.62, 0.81, 0.22, 0.85, 0.57],
       [0.14, 0.89, 0.06, 0.24, 0.86, 0.11, 0.72, 0.01, 0.87, 0.7 ],
       [0.84, 0.48, 0.25, 0.38, 0.11, 0.33, 0.31, 0.07, 0.87, 0.39],
       [0.96, 0.39, 0.49, 0.93, 0.49, 0.34, 0.28, 0.42, 0.62, 1.  ],
       [0.34, 0.36, 0.97, 0.3 , 0.76, 0.01, 0.02, 0.09, 0.12, 0.  ],
       [0.21, 0.67, 0.92, 0.73, 0.5 , 0.91, 0.82, 0.24, 0.25, 0.88],
       [0.78, 0.54, 0.21, 0.42, 0.48, 0.43, 0.23, 0.44, 0.16, 0.42],
       [0.97, 0.76, 0.45, 0.42, 0.88, 0.48, 0.93, 0.94, 0.96, 0.38]])

In [13]:
# Splicing works perfectly. See these examples:
print("=== Without step ===")
print(beta[3:7, 2:5])
print("=== With step ===")
print(beta[1:8:3, 2:9:2])

=== Without step ===
[[0.06 0.24 0.86]
 [0.25 0.38 0.11]
 [0.49 0.93 0.49]
 [0.97 0.3  0.76]]
=== With step ===
[[0.01 0.92 0.88 0.43]
 [0.25 0.11 0.31 0.87]
 [0.92 0.5  0.82 0.25]]


In [14]:
# NumPy Arrays are mutable.
beta[3, 6] = 1000
beta

array([[9.4e-01, 7.4e-01, 4.4e-01, 1.1e-01, 1.8e-01, 2.0e-01, 9.1e-01,
        4.2e-01, 5.6e-01, 4.3e-01],
       [6.9e-01, 7.8e-01, 1.0e-02, 2.5e-01, 9.2e-01, 5.7e-01, 8.8e-01,
        7.8e-01, 4.3e-01, 9.0e-02],
       [7.4e-01, 3.7e-01, 8.9e-01, 3.0e-01, 7.8e-01, 6.2e-01, 8.1e-01,
        2.2e-01, 8.5e-01, 5.7e-01],
       [1.4e-01, 8.9e-01, 6.0e-02, 2.4e-01, 8.6e-01, 1.1e-01, 1.0e+03,
        1.0e-02, 8.7e-01, 7.0e-01],
       [8.4e-01, 4.8e-01, 2.5e-01, 3.8e-01, 1.1e-01, 3.3e-01, 3.1e-01,
        7.0e-02, 8.7e-01, 3.9e-01],
       [9.6e-01, 3.9e-01, 4.9e-01, 9.3e-01, 4.9e-01, 3.4e-01, 2.8e-01,
        4.2e-01, 6.2e-01, 1.0e+00],
       [3.4e-01, 3.6e-01, 9.7e-01, 3.0e-01, 7.6e-01, 1.0e-02, 2.0e-02,
        9.0e-02, 1.2e-01, 0.0e+00],
       [2.1e-01, 6.7e-01, 9.2e-01, 7.3e-01, 5.0e-01, 9.1e-01, 8.2e-01,
        2.4e-01, 2.5e-01, 8.8e-01],
       [7.8e-01, 5.4e-01, 2.1e-01, 4.2e-01, 4.8e-01, 4.3e-01, 2.3e-01,
        4.4e-01, 1.6e-01, 4.2e-01],
       [9.7e-01, 7.6e-01, 4.5e-01, 4.

In [15]:
# We can also input the change through the spliced arrays also which will reflect in the main array.
beta[1:8:3, 2:9:2] = [[-1, -1, -1, -1], [-1, -1, -1, -1], [-1, -1, -1, -1]]  # or np.full((3, 4), -1)
beta

array([[ 9.4e-01,  7.4e-01,  4.4e-01,  1.1e-01,  1.8e-01,  2.0e-01,
         9.1e-01,  4.2e-01,  5.6e-01,  4.3e-01],
       [ 6.9e-01,  7.8e-01, -1.0e+00,  2.5e-01, -1.0e+00,  5.7e-01,
        -1.0e+00,  7.8e-01, -1.0e+00,  9.0e-02],
       [ 7.4e-01,  3.7e-01,  8.9e-01,  3.0e-01,  7.8e-01,  6.2e-01,
         8.1e-01,  2.2e-01,  8.5e-01,  5.7e-01],
       [ 1.4e-01,  8.9e-01,  6.0e-02,  2.4e-01,  8.6e-01,  1.1e-01,
         1.0e+03,  1.0e-02,  8.7e-01,  7.0e-01],
       [ 8.4e-01,  4.8e-01, -1.0e+00,  3.8e-01, -1.0e+00,  3.3e-01,
        -1.0e+00,  7.0e-02, -1.0e+00,  3.9e-01],
       [ 9.6e-01,  3.9e-01,  4.9e-01,  9.3e-01,  4.9e-01,  3.4e-01,
         2.8e-01,  4.2e-01,  6.2e-01,  1.0e+00],
       [ 3.4e-01,  3.6e-01,  9.7e-01,  3.0e-01,  7.6e-01,  1.0e-02,
         2.0e-02,  9.0e-02,  1.2e-01,  0.0e+00],
       [ 2.1e-01,  6.7e-01, -1.0e+00,  7.3e-01, -1.0e+00,  9.1e-01,
        -1.0e+00,  2.4e-01, -1.0e+00,  8.8e-01],
       [ 7.8e-01,  5.4e-01,  2.1e-01,  4.2e-01,  4.8e-01,  4.3e-

## Initializing Different Types of Arrays

In [16]:
# All zeroes matrix
null = np.zeros((3, 4))
null

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# All 'ones' matrix
ones = np.ones((4, 3, 2), dtype='int32')
ones

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [18]:
# Any other number
full = np.full((3, 2), 99)
full

array([[99, 99],
       [99, 99],
       [99, 99]])

In [19]:
# To take the dimensions of a matrix and fill it with a number: (Note: The first argument is an array, not its dimensions.)
full_like = np.full_like(b, 6)
full_like

array([[6., 6., 6.],
       [6., 6., 6.]])

In [20]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# Repeat an array (Kind of...)
arr_to_rep = np.array([[1, 2, 3]])
rep_array = np.repeat(arr_to_rep, 5, axis=0)
rep_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Random Arrays

In [22]:
# Type 1: Argument is the dimension Iterable
np.random.random_sample((4, 2))

array([[0.86608154, 0.22246123],
       [0.21671812, 0.75628946],
       [0.13429037, 0.73114568],
       [0.82560863, 0.43362054]])

In [23]:
# Type 2: Unpacked Arguments
np.random.rand(4, 2)

array([[0.22005944, 0.18654279],
       [0.06498921, 0.25194607],
       [0.284606  , 0.70902958],
       [0.59103144, 0.35461195]])

In [24]:
# Random Integer Values
np.random.randint(7, size=(3, 3))  # The 7 here is the higher limit. If we aren't passing both the low and high arguments, it is considered as high, and it should be > 0.

array([[1, 1, 2],
       [6, 3, 3],
       [2, 2, 6]])

### Exercise:
Try to get this array without manually typing:<br>
[[1, 1, 1, 1, 1],<br>
 [1, 0, 0, 0, 1],<br>
 [1, 0, 9, 0, 1],<br>
 [1, 0, 0, 0, 1],<br>
 [1, 1, 1, 1, 1]]

In [25]:
exercise = np.ones((5, 5))
exercise[1:-1, 1:-1] = np.zeros((3, 3))
exercise[2, 2] = 9
exercise

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Copying arrays

In [26]:
omegaA = np.array([1, 2, 3])
phiA = omegaA
phiA[0] = 100
omegaA

array([100,   2,   3])

In [27]:
omegaB = np.array([1, 2, 3])
phiB = omegaB.copy()
phiB[0] = 100
omegaB

array([1, 2, 3])

## Mathematics

In [28]:
a_M = np.array([1, 2, 5, 7])
print(a_M + 2, a_M * 2, sep='\n')  # a_M - 2, a_M / 2 and a_M ** 2 also work. Other overloaded operations such as +=, -= ... also work. (Broadcasting for a + 2)

[3 4 7 9]
[ 2  4 10 14]


In [29]:
# np.sin([array]) gives the sine of each term in the array
np.sin(beta)

array([[ 0.8075581 ,  0.67428791,  0.42593947,  0.1097783 ,  0.17902957,
         0.19866933,  0.78950374,  0.40776045,  0.5311862 ,  0.4168708 ],
       [ 0.63653718,  0.70327942, -0.84147098,  0.24740396, -0.84147098,
         0.53963205, -0.84147098,  0.70327942, -0.84147098,  0.08987855],
       [ 0.67428791,  0.36161543,  0.77707175,  0.29552021,  0.70327942,
         0.58103516,  0.72428717,  0.21822962,  0.75128041,  0.53963205],
       [ 0.13954311,  0.77707175,  0.05996401,  0.23770263,  0.75784256,
         0.1097783 ,  0.82687954,  0.00999983,  0.76432894,  0.64421769],
       [ 0.74464312,  0.46177918, -0.84147098,  0.37092047, -0.84147098,
         0.32404303, -0.84147098,  0.06994285, -0.84147098,  0.38018842],
       [ 0.81919157,  0.38018842,  0.47062589,  0.80161994,  0.47062589,
         0.33348709,  0.27635565,  0.40776045,  0.58103516,  0.84147098],
       [ 0.33348709,  0.35227423,  0.82488571,  0.29552021,  0.68892145,
         0.00999983,  0.01999867,  0.08987855

## Linear Algebra